import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ALL_TOOLS, hasVerifiedScore, computeOverall } from '@/data/tools';
import { GRAVEYARD } from '@/data/graveyard';
import { SITE_URL, SITE_NAME, MIN_REVIEWS_FOR_AGGREGATE_RATING } from '@/config/site';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { ToolCard } from '@/components/ToolCard';
import { CompareBar } from '@/components/CompareBar';
import { ReviewSection } from '@/components/ReviewSection';
import { ToolActions } from '@/components/ToolActions';
import { EvidenceCard } from '@/components/EvidenceCard';
import { ScoreBreakdown } from '@/components/ScoreBreakdown';
import { VerificationBadge, NotTestedNotice } from '@/components/VerificationBadge';
import { SmartImage } from '@/components/SmartImage';
import { getApprovedReviewStats } from '@/lib/reviewStats';
import {
  ExternalLink,
  ArrowLeft,
  CalendarCheck,
  Tag,
  DollarSign,
  Award,
  TrendingUp,
} from 'lucide-react';

export const dynamicParams = false;

export function generateStaticParams() {
  return ALL_TOOLS.map((t) => ({ slug: t.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const tool = ALL_TOOLS.find((t) => t.slug === slug);
  if (!tool) return { title: 'Tool Not Found' };

  const tested = hasVerifiedScore(tool);

  /**
   * Audit fix 1.1 — the old title promised "Review 2026" for 153 tools that
   * had never been reviewed. Titles now match what the page actually contains.
   */
  const title = tested
    ? `${tool.name} Review 2026: Tested, Priced & Compared`
    : `${tool.name}: Pricing, Features & Alternatives (2026)`;

  const description = tested
    ? `Hands-on ${tool.name} review. ${tool.tagline}. We scored it ${computeOverall(
        tool.scores!
      )}/10 on output quality, speed, value and export freedom. Pricing from ${
        tool.startingPrice ?? 'free'
      }.`
    : `${tool.name}: ${tool.tagline}. ${tool.description.slice(0, 110)}… Pricing: ${tool.pricing}${
        tool.startingPrice ? ` from ${tool.startingPrice}` : ''
      }. Compare against ${tool.category} alternatives.`;

  return {
    title,
    description,
    alternates: { canonical: `/tool/${tool.slug}` },
    openGraph: {
      title,
      description,
      url: `/tool/${tool.slug}`,
      type: 'article',
      // Dynamic OG image (audit fix 3.2) is generated by opengraph-image.tsx.
    },
    twitter: { card: 'summary_large_image', title, description },
  };
}

function priceNumber(s?: string): string | undefined {
  const m = s?.match(/[\d.]+/);
  return m ? m[0] : undefined;
}

export default async function ToolDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const tool = ALL_TOOLS.find((t) => t.slug === slug);
  if (!tool) notFound();

  const tested = hasVerifiedScore(tool);
  const overall = tested && tool.scores ? computeOverall(tool.scores) : null;

  /**
   * Audit fix 1.2 — real approved review counts, read at build time.
   * The old code emitted ratingCount: Math.max(tool.reviewsCount, 1), which
   * told Google "1 person rated this 4.8" for 153 tools with zero reviews.
   * That is textbook structured-data spam.
   */
  const reviewStats = await getApprovedReviewStats(tool.slug);

  const alternatives = ALL_TOOLS.filter((t) => t.slug !== tool.slug && t.category === tool.category)
    .sort((a, b) => {
      const av = hasVerifiedScore(a) ? 1 : 0;
      const bv = hasVerifiedScore(b) ? 1 : 0;
      if (av !== bv) return bv - av;
      return b.rating - a.rating;
    })
    .slice(0, 4);

  const related = ALL_TOOLS.filter(
    (t) =>
      t.slug !== tool.slug &&
      t.category !== tool.category &&
      t.tags.some((tag) => tool.tags.includes(tag))
  ).slice(0, 4);

  // Dead tools that this one replaces — turns the graveyard into inbound links.
  const replaces = GRAVEYARD.filter((d) => d.replacements.includes(tool.slug));

  const jsonLd: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: tool.name,
    description: tool.description,
    url: tool.url,
    applicationCategory: 'MultimediaApplication',
    operatingSystem: 'Web',
    offers: {
      '@type': 'Offer',
      price: priceNumber(tool.startingPrice) || '0',
      priceCurrency: 'USD',
      description: tool.pricing,
      ...(tool.pricingSourceUrl && { url: tool.pricingSourceUrl }),
    },
  };

  // aggregateRating ONLY with enough genuine approved reviews (audit fix 1.2).
  if (reviewStats.count >= MIN_REVIEWS_FOR_AGGREGATE_RATING) {
    jsonLd.aggregateRating = {
      '@type': 'AggregateRating',
      ratingValue: reviewStats.average,
      bestRating: 5,
      worstRating: 1,
      ratingCount: reviewStats.count,
    };
  }

  // A single editorial Review is always legitimate — but only when we tested it.
  if (tested && overall !== null) {
    jsonLd.review = {
      '@type': 'Review',
      author: { '@type': 'Organization', name: `${SITE_NAME} Editorial Team` },
      datePublished: tool.testedAt,
      reviewRating: {
        '@type': 'Rating',
        ratingValue: Math.round((overall / 2) * 10) / 10, // 0–10 → 0–5
        bestRating: 5,
        worstRating: 1,
      },
      reviewBody: tool.verdict?.bestFor ?? tool.description,
    };
  }

  const breadcrumbLd = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL },
      { '@type': 'ListItem', position: 2, name: 'All Tools', item: `${SITE_URL}/tools` },
      {
        '@type': 'ListItem',
        position: 3,
        name: tool.category,
        item: `${SITE_URL}/category/${encodeURIComponent(
          tool.category.toLowerCase().replace(/[^a-z0-9]+/g, '-')
        )}`,
      },
      { '@type': 'ListItem', position: 4, name: tool.name, item: `${SITE_URL}/tool/${tool.slug}` },
    ],
  };

  return (
    <div className="min-h-screen bg-surface-0 text-foreground">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }}
      />
      <Header />

      <main id="main" className="mx-auto max-w-5xl px-4 py-10">
        <Link
          href="/tools"
          className="mb-6 inline-flex items-center gap-1.5 text-2xs font-semibold text-zinc-400 transition-colors hover:text-accent-400"
        >
          <ArrowLeft className="h-3.5 w-3.5" aria-hidden="true" /> Back to All Tools
        </Link>

        {/* Hero */}
        <div className="relative overflow-hidden rounded-3xl border border-white/10">
          <div className="relative h-56 sm:h-72">
            <SmartImage
              src={tool.coverImage}
              alt=""
              fill
              priority
              sizes="(max-width: 1024px) 100vw, 1024px"
              className="object-cover"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-surface-0 via-black/50 to-transparent" />
          </div>
          <div className="relative -mt-16 px-6 pb-6 sm:px-8">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-end">
              <SmartImage
                src={tool.logo}
                alt={`${tool.name} logo`}
                width={80}
                height={80}
                className="h-20 w-20 rounded-2xl border border-white/10 bg-surface-2 object-cover shadow-2xl"
              />
              <div className="flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <h1 className="text-3xl font-black tracking-tight">{tool.name}</h1>
                  {tool.isEditorsChoice && tested && (
                    <span className="inline-flex items-center gap-1 rounded-full bg-accent-500 px-2.5 py-1 text-2xs font-bold text-black">
                      <Award className="h-3 w-3" aria-hidden="true" /> Editor&apos;s Choice
                    </span>
                  )}
                  {tool.isTrending && (
                    <span className="inline-flex items-center gap-1 rounded-full bg-rose-500/90 px-2.5 py-1 text-2xs font-bold text-white">
                      <TrendingUp className="h-3 w-3" aria-hidden="true" /> Trending
                    </span>
                  )}
                </div>
                <p className="mt-1 text-sm text-zinc-300">{tool.tagline}</p>
                <div className="mt-2">
                  <VerificationBadge
                    level={tool.verificationLevel}
                    testedAt={tool.testedAt}
                  />
                </div>
              </div>
              <div className="flex items-center gap-2">
                <ToolActions slug={tool.slug} name={tool.name} />
                <a
                  href={`/go/${tool.slug}`}
                  target="_blank"
                  rel={
                    tool.affiliateProgram
                      ? 'noopener noreferrer nofollow sponsored'
                      : 'noopener noreferrer nofollow'
                  }
                  className="inline-flex items-center gap-2 rounded-2xl bg-accent-500 px-6 py-3 text-sm font-bold text-black shadow-lg shadow-accent-500/20 transition-opacity hover:opacity-90"
                >
                  Visit {tool.name} <ExternalLink className="h-4 w-4" aria-hidden="true" />
                </a>
              </div>
            </div>
          </div>
        </div>

        {/* Quick facts */}
        <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
          <div className="rounded-2xl border border-white/10 bg-surface-1 p-4">
            <div className="flex items-center gap-1.5 text-2xs font-bold uppercase tracking-wide text-zinc-500">
              <Award className="h-3 w-3" aria-hidden="true" /> Our score
            </div>
            {/* Audit fix 2.1 — no invented number when we have not tested it. */}
            {overall !== null ? (
              <div className="mt-1 flex items-baseline gap-1">
                <span className="font-mono text-xl font-black tabular-nums text-white">
                  {overall.toFixed(1)}
                </span>
                <span className="text-2xs text-zinc-500">/ 10</span>
              </div>
            ) : (
              <div className="mt-1 text-sm font-semibold text-zinc-500">Not yet tested</div>
            )}
          </div>

          <div className="rounded-2xl border border-white/10 bg-surface-1 p-4">
            <div className="flex items-center gap-1.5 text-2xs font-bold uppercase tracking-wide text-zinc-500">
              <DollarSign className="h-3 w-3" aria-hidden="true" /> Pricing
            </div>
            <div className="mt-1 text-sm font-bold text-emerald-400">
              {tool.pricing}
              {tool.startingPrice ? ` · ${tool.startingPrice}` : ''}
            </div>
            {/* Audit fix 2.3 — price claims now cite a source and a date. */}
            {tool.pricingSourceUrl && tool.pricingCheckedAt && (
              <a
                href={tool.pricingSourceUrl}
                target="_blank"
                rel="noopener noreferrer nofollow"
                className="mt-1 block text-2xs text-zinc-500 underline hover:text-zinc-300"
              >
                Source · checked {tool.pricingCheckedAt}
              </a>
            )}
          </div>

          <div className="rounded-2xl border border-white/10 bg-surface-1 p-4">
            <div className="flex items-center gap-1.5 text-2xs font-bold uppercase tracking-wide text-zinc-500">
              <Tag className="h-3 w-3" aria-hidden="true" /> Category
            </div>
            <Link
              href={`/tools?category=${encodeURIComponent(tool.category)}`}
              className="mt-1 block text-sm font-bold text-white hover:text-accent-300"
            >
              {tool.category}
            </Link>
          </div>

          <div className="rounded-2xl border border-white/10 bg-surface-1 p-4">
            <div className="flex items-center gap-1.5 text-2xs font-bold uppercase tracking-wide text-zinc-500">
              <CalendarCheck className="h-3 w-3" aria-hidden="true" />
              {tested ? 'Tested on' : 'Listed'}
            </div>
            <div className="mt-1 text-sm font-bold text-white">
              {tested ? (
                <span className="font-mono tabular-nums">{tool.testedAt}</span>
              ) : tool.pricingCheckedAt ? (
                <span className="font-mono tabular-nums">{tool.pricingCheckedAt}</span>
              ) : (
                // Better than a bare dash: says what the state actually is.
                <span className="text-zinc-500">In catalog</span>
              )}
            </div>
          </div>
        </div>

        {/*
          Audit fix 1.1 — the Evidence Card is now conditional. Previously an
          identical hardcoded card claiming "Hands-on + Vendor Data" appeared
          on all 200 pages, including 153 machine-generated entries.
        */}
        {tested ? <EvidenceCard tool={tool} /> : <NotTestedNotice toolName={tool.name} />}

        {tested && tool.scores && <ScoreBreakdown scores={tool.scores} verdict={tool.verdict} />}

        {/* Pros & cons — audit fix 2.1: no tool previously listed a drawback. */}
        {(tool.pros?.length || tool.cons?.length) && (
          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            {tool.pros?.length ? (
              <section className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5">
                <h2 className="mb-3 text-sm font-bold text-emerald-300">What we liked</h2>
                <ul className="space-y-2">
                  {tool.pros.map((p) => (
                    <li key={p} className="flex gap-2 text-sm text-zinc-300">
                      <span aria-hidden="true" className="text-emerald-400">
                        +
                      </span>
                      {p}
                    </li>
                  ))}
                </ul>
              </section>
            ) : null}
            {tool.cons?.length ? (
              <section className="rounded-2xl border border-rose-500/20 bg-rose-500/5 p-5">
                <h2 className="mb-3 text-sm font-bold text-rose-300">What held it back</h2>
                <ul className="space-y-2">
                  {tool.cons.map((c) => (
                    <li key={c} className="flex gap-2 text-sm text-zinc-300">
                      <span aria-hidden="true" className="text-rose-400">
                        −
                      </span>
                      {c}
                    </li>
                  ))}
                </ul>
              </section>
            ) : null}
          </div>
        )}

        {/* Description */}
        <section className="mt-8 rounded-3xl border border-white/10 bg-surface-1 p-6 sm:p-8">
          <h2 className="mb-3 text-lg font-bold">What is {tool.name}?</h2>
          <p className="text-sm leading-relaxed text-zinc-300">{tool.description}</p>
          {tool.metrics && (
            <p className="mt-3 inline-flex items-center gap-2 rounded-xl border border-accent-500/20 bg-accent-500/10 px-3 py-2 text-2xs font-semibold text-accent-300">
              Standout metric: {tool.metrics}
            </p>
          )}
          <div className="mt-4 flex flex-wrap gap-1.5">
            {tool.tags.map((tag) => (
              <Link
                key={tag}
                href={`/tools?q=${encodeURIComponent(tag)}`}
                className="rounded-md border border-white/10 bg-surface-2 px-2.5 py-1 text-2xs text-zinc-400 transition-colors hover:border-accent-500/30 hover:text-accent-300"
              >
                #{tag}
              </Link>
            ))}
          </div>

          {/* Honest editorial footer — no blanket "we test everything" claim. */}
          <p className="mt-5 border-t border-white/5 pt-4 text-2xs leading-relaxed text-zinc-500">
            {tested ? (
              <>
                Tested by the {SITE_NAME} editorial team on {tool.testedAt}
                {tool.planTested ? ` using the ${tool.planTested} plan` : ''}.{' '}
              </>
            ) : (
              <>
                This entry is catalogued from public sources — we have not run {tool.name}{' '}
                ourselves.{' '}
              </>
            )}
            <Link href="/about" className="underline hover:text-zinc-300">
              Read our methodology
            </Link>
            .{' '}
            {tool.affiliateProgram && (
              <>
                Links to {tool.name} are affiliate links (
                <Link href="/disclosure" className="underline hover:text-zinc-300">
                  disclosure
                </Link>
                ).
              </>
            )}
          </p>
        </section>

        {replaces.length > 0 && (
          <section className="mt-6 rounded-2xl border border-white/10 bg-surface-1 p-5">
            <h2 className="text-sm font-bold text-zinc-200">Migrating from a discontinued tool?</h2>
            <p className="mt-2 text-sm text-zinc-400">
              We recommend {tool.name} as a replacement for{' '}
              {replaces.map((d, i) => (
                <span key={d.slug}>
                  {i > 0 && ', '}
                  <Link href="/graveyard" className="text-accent-400 underline hover:text-accent-300">
                    {d.name}
                  </Link>
                </span>
              ))}
              , which {replaces.length === 1 ? 'is' : 'are'} no longer available.
            </p>
          </section>
        )}

        <ReviewSection toolSlug={tool.slug} toolName={tool.name} />

        {alternatives.length > 0 && (
          <section className="mt-12">
            <h2 className="mb-1 text-xl font-bold">
              Top {tool.name} Alternatives
            </h2>
            <p className="mb-5 text-2xs text-zinc-500">
              Other {tool.category} tools worth comparing.{' '}
              <Link
                href={`/alternatives/${tool.slug}`}
                className="text-accent-400 underline hover:text-accent-300"
              >
                See the full comparison →
              </Link>
            </p>
            <ul className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
              {alternatives.map((t, i) => (
                <li key={t.slug}>
                  <ToolCard tool={t} index={i} />
                </li>
              ))}
            </ul>
          </section>
        )}

        {related.length > 0 && (
          <section className="mt-12">
            <h2 className="mb-1 text-xl font-bold">Pairs Well With</h2>
            <p className="mb-5 text-2xs text-zinc-500">
              Tools creators commonly stack with {tool.name}.
            </p>
            <ul className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
              {related.map((t, i) => (
                <li key={t.slug}>
                  <ToolCard tool={t} index={i} />
                </li>
              ))}
            </ul>
          </section>
        )}
      </main>

      <CompareBar />
      <Footer />
    </div>
  );
}
