-- 0017_ai_usage_daily.sql
-- Persistent daily usage counters and an append-only audit log for Studio Pro.
-- The previous ai_quota/account summary used a best-effort in-memory map that
-- reset on every serverless cold start and could be trivially bypassed with a
-- forged email in the request body. These two tables are the server truth.

create table if not exists public.ai_usage_daily (
  identifier text not null,
  day date not null,
  used integer not null default 0,
  primary key (identifier, day)
);

alter table public.ai_usage_daily enable row level security;
-- No direct client access. Only the service role (via supabaseAdmin) reads
-- and writes these rows through the server routes.

create index if not exists ai_usage_daily_day_idx on public.ai_usage_daily (day desc);

comment on table public.ai_usage_daily is
  'Daily AI generation usage counters. identifier is user:<email> or ip:<ip>.';

-- Append-only audit trail for Studio Pro / payment-related events.
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  action text not null,
  entity text,
  detail jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;

comment on table public.admin_audit_log is
  'Append-only audit trail for sensitive server actions (payments, admin changes).';
