import type { VerifiedRecord } from './tools';

/**
 * ════════════════════════════════════════════════════════════════════════
 *  THE EVIDENCE REGISTRY — the only place a trust claim can be granted.
 * ════════════════════════════════════════════════════════════════════════
 *
 * Audit fixes 1.1, 1.2, 2.1, 2.3.
 *
 * WHY THIS FILE EXISTS
 * Before this change, every one of the 200 tool pages rendered an identical
 * "Evidence Card — How We Tested {tool}" reading "Test Date: 2026-08-01,
 * Evidence Type: Hands-on + Vendor Data", and the header claimed
 * "Independently tested". In reality 153 tools were generated by
 * scripts/gen-tools.mjs with reviewsCount: 0 and invented ratings. That
 * combination — an unproven test claim sitting next to an affiliate link — is
 * exactly what Google's scaled-content-abuse policy and FTC 16 CFR Part 255
 * target, and a single screenshot of it on social media would end the site's
 * credibility on day one.
 *
 * ─────────────────────────────────────────────────────────────────────────
 *  THE RULE
 * ─────────────────────────────────────────────────────────────────────────
 * A tool shows an Evidence Card and a numeric score ONLY if it appears below
 * with verificationLevel: 'hands-on-tested', a real testedAt date, real
 * sub-scores, and at least one evidenceUrl. Anything absent from this file is
 * automatically 'listed-only' and the UI says so plainly.
 *
 * ⚠️  DO NOT add a 'hands-on-tested' entry for a tool you have not personally
 *     run. The whole point of this file is that the claim is true. An empty
 *     registry is honest; a full one built on guesses is the original problem
 *     wearing a new type signature.
 *
 * ─────────────────────────────────────────────────────────────────────────
 *  HOW TO PROMOTE A TOOL AFTER YOU TEST IT   (this is your weekly workflow)
 * ─────────────────────────────────────────────────────────────────────────
 *   1. Actually run the tool on the standard brief for its category
 *      (see /benchmark for the five briefs).
 *   2. Capture evidence: a screenshot of the output, the exported file, or a
 *      short clip. Upload it and put the URL in evidenceUrls.
 *   3. Score each dimension 0–10 honestly. Use the full range —
 *      a 5/10 is a normal, useful score. If nothing ever scores below 7 the
 *      scores carry no information and readers will notice.
 *   4. Fill pros AND cons. Every tool has real drawbacks; listing none is the
 *      single loudest "this page exists for the commission" signal there is.
 *   5. Set testedAt to the date you ran it and planTested to the plan you paid
 *      for. Re-test or downgrade the claim when it goes stale (~6 months).
 *
 * Template:
 *
 *   'tool-slug': {
 *     verificationLevel: 'hands-on-tested',
 *     testedAt: '2026-08-14',
 *     planTested: 'Pro — $29/mo',
 *     evidenceUrls: ['https://.../opusclip-test-output.mp4'],
 *     scores: { outputQuality: 8, speed: 9, valueForMoney: 7,
 *               easeOfUse: 9, exportFreedom: 6 },
 *     verdict: { bestFor: '…', skipIf: '…' },
 *     pros: ['…'], cons: ['…'],
 *     startingPrice: '$29/mo',
 *     pricingSourceUrl: 'https://vendor.com/pricing',
 *     pricingCheckedAt: '2026-08-14',
 *   },
 */
export const VERIFIED_TOOLS: Record<string, VerifiedRecord> = {
  /* ══════════════════════════════════════════════════════════════════════
   *  PRICING-VERIFIED
   *  A human opened the vendor's own pricing page and confirmed the number.
   *  This is a real, checkable claim — and it is deliberately weaker than
   *  "we tested it". No sub-scores, no Evidence Card, no numeric verdict.
   * ══════════════════════════════════════════════════════════════════════ */

  opusclip: {
    verificationLevel: 'pricing-verified',
    // Audit fix 2.3: the site listed $9.99/mo on its flagship tool. The real
    // entry paid tier is Starter at $15/mo (Free tier exists but watermarks
    // exports). Publishing a wrong price under a "Pricing verified" banner
    // invalidated the banner.
    startingPrice: '$15/mo',
    pricingSourceUrl: 'https://www.opus.pro/pricing',
    pricingCheckedAt: '2026-08-03',
  },

  elevenlabs: {
    verificationLevel: 'pricing-verified',
    startingPrice: '$5/mo',
    pricingSourceUrl: 'https://elevenlabs.io/pricing',
    pricingCheckedAt: '2026-08-03',
  },

  /* ══════════════════════════════════════════════════════════════════════
   *  HANDS-ON TESTED
   *  Intentionally empty.
   *
   *  Populating this with invented test data would recreate precisely the
   *  violation this refactor removes. The plumbing is finished and proven —
   *  the Evidence Card, the sub-score radar, the "Tested" filter and the
   *  Review structured data all light up the moment you add your first real
   *  entry using the template above.
   *
   *  Recommended first batch (highest traffic, all in your top categories):
   *    opusclip · descript · elevenlabs · runway · heygen · submagic ·
   *    capcut · veed · vizard · klap
   *
   *  Ten genuinely tested tools beat two hundred claimed ones — that is the
   *  entire competitive moat described in section 7.1 of the audit.
   * ══════════════════════════════════════════════════════════════════════ */
};

/** Slugs with a real hands-on test on file. */
export const HANDS_ON_SLUGS = Object.entries(VERIFIED_TOOLS)
  .filter(([, v]) => v.verificationLevel === 'hands-on-tested')
  .map(([slug]) => slug);
